---
title: "`r gsub('.Rmd', ' ', gsub('_', ' ', knitr::current_input()))`"
author: "Report generated by `r Sys.getenv('USER')` at `r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
output:
  html_document:
    toc: yes
params:
  date: !r Sys.Date()
  Sample: "TH34_2292_S01"
  Gene: "P2RY11"
  Expression: "5.47"
  Threshold: "5.46"
  Type: "up"
  Depth: "3.5"
  Length: "1200"

---


```{r setup, include = FALSE}

library(readr)
library(jsonlite)
library(magrittr)
library(dplyr)
library(tidyr)
library(knitr)
library(stringr)
library(tibble)

```

### Background

The purpose of this Rmd is to quantify the accuracy of outlier leads.

### Read in data

```{r echo = TRUE}

sample_id <- params$Sample
outlier_lead <- params$Gene
exp <- params$Expression
threshold <- params$Threshold
type <- params$Type
mend_depth <- params$Depth
gene_length <- params$Length

```

### Add bin info

```{r echo = TRUE}

# start scratch (uncomment this to manually set things to run code)
# 
# sample_id <- "TH_Eval_014_est10M_UMEND_seqtk_seed_8652"
# outlier_lead <- "SGCA"
# exp <- 3.6
# threshold <- 3.5
# type <- "Up"
# mend_depth <- 1000000
# gene_length <- 100
#
# end scratch

if (exp >= 20) {
  stop("expression >= 20. make sure your expression is in log2(TPM+1)")
}

expression_bin_boundaries <- c(0, 1, 3, 5, 7, 10, 20)
mend_depth_bin_boundaries <- c(0, seq(2, 46, 4), Inf)*1E6
length_bin_boundaries <- c(0, 100, 450, 800, 1500, 4000, Inf)

make_bin_names <- function(boundaries = 1:10){
  raw_names <- paste0(boundaries, "-", lead(boundaries)) %>% str_replace("-Inf", "+")
  raw_names[1:(length(boundaries)-1)]
}
  
expression_bin_names <- make_bin_names(expression_bin_boundaries)
mend_depth_bin_names <- make_bin_names(mend_depth_bin_boundaries/1e6)
length_bin_names <- make_bin_names(length_bin_boundaries)

expression_bin <- cut(exp, expression_bin_boundaries,
                      labels = expression_bin_names, include.lowest = TRUE)
mend_depth_bin <- cut(mend_depth, mend_depth_bin_boundaries,
                      labels = mend_depth_bin_names, include.lowest = TRUE)
length_bin <- cut(gene_length, length_bin_boundaries,
                  labels = length_bin_names, include.lowest = TRUE)

```

### Get all relevant accuracy measurements for each threshold

```{r echo = TRUE}

# Start building summary table

threshold <- as.numeric(threshold)
exp <- as.numeric(exp)

summary <- tibble(sample = sample_id,
                  gene = outlier_lead,
                  type = type,
                  expression = exp,
                  threshold = threshold,
                  mend_depth = mend_depth,
                  gene_length = gene_length)

# Calculate percent difference

summary <- summary %>%
  mutate(percent_difference = 100 * ((abs(expression - threshold)) / expression))

# Get accuracy distributions

if (!(is.na(summary$percent_difference))) {
  # Set accuracy threshold and get accuracy info
  non_zero_abundance <- per_gene_expression_info %>%
    mutate(within_accuracy_threshold_of_deepest_val =
             expression > (1 - summary$percent_difference / 100) * expression_at_max_depth &
             expression < (1 + summary$percent_difference / 100) * expression_at_max_depth)
  # Make expression bins and generate summary statistics
  abundance_by_expression_bin <- non_zero_abundance %>% 
    ungroup() %>% 
    mutate(expression_level_bin = cut(expression_at_max_depth, expression_bin_boundaries,
                      labels = expression_bin_names, include.lowest = TRUE),
           effective_gene_length_bin = cut(effective_gene_length, length_bin_boundaries,
                  labels = length_bin_names, include.lowest = TRUE),
           depth_bin = cut(UMEND, mend_depth_bin_boundaries,
                      labels = mend_depth_bin_names, include.lowest = TRUE))
  abundance_stats <- abundance_by_expression_bin	%>% 
    group_by(expression_level_bin, depth_bin, effective_gene_length_bin, parent_id) %>%
    summarize(pct_accurately_measured = sum(within_accuracy_threshold_of_deepest_val) / n(),
              n_genes_in_bin = length(unique(gene)),
              n_measurements_in_bin = n())
}

# Filter results

if (!(is.null(abundance_stats))) {
  stats_filtered <- abundance_stats %>%
    ungroup %>%
    filter((depth_bin == mend_depth_bin) & 
             (expression_level_bin == expression_bin) & 
             (effective_gene_length_bin == length_bin)) %>%
    arrange(parent_id)
}

```

### Calculate gene expression measurement accuracy stats

```{r echo = TRUE, warning = FALSE}

# Get accuracy stats

summary <- summary %>%
  mutate(
    avg = mean(stats_filtered$pct_accurately_measured),
    min = min(stats_filtered$pct_accurately_measured),
    max = max(stats_filtered$pct_accurately_measured),
    S1 = stats_filtered$pct_accurately_measured[1],
    S2 = stats_filtered$pct_accurately_measured[2],
    S3 = stats_filtered$pct_accurately_measured[3],
    S4 = stats_filtered$pct_accurately_measured[4],
    S5 = stats_filtered$pct_accurately_measured[5]
  )

```

### Write summary to tsv and show tables

```{r echo = TRUE}

# Add column that checks if probability >= 0.95

summary <- add_column(summary, prob95 = summary$avg >= 0.95, .after = "percent_difference")

# Clean up names for writing to outfile
# If accuracy analysis fails QC, report NA instead of Avg for probability

names(summary) <- gsub("_", " ", str_to_sentence(names(summary)))

summary <- summary %>%
  mutate(Avg = ifelse((sum(stats_filtered$n_measurements_in_bin) < 100 | nrow(stats_filtered) < 5), NA, Avg)) %>%
  rename("Probability >= 0.95" = Prob95,
         "Probability of being an outlier" = Avg,
         "Minimum Probability" = Min,
         "Maximum Probability" = Max,
         "Sample 1 Probability" = S1,
         "Sample 2 Probability" = S2,
         "Sample 3 Probability" = S3,
         "Sample 4 Probability" = S4,
         "Sample 5 Probability" = S5)

# Write to outfile

if ( ! dir.exists(paste0("results/", sample_id))) dir.create(paste0("results/", sample_id))
write_tsv(summary, paste0("results/", sample_id, "/sample_", sample_id, "__gene_", outlier_lead, "__summary.tsv"))

# Show short summary table & long summary table

kable(summary[1:10], digits = 4)
kable(summary, digits = 4)

# If there are fewer than 100 measurements considered, print a warning message
if (sum(stats_filtered$n_measurements_in_bin) < 100) {
  print("Warning: this outlier probability estimate is based on <100 similar measurements")
}

# If there were not data for all 5 parent samples, print a warning message
if (nrow(stats_filtered) < 5) {
  print("Warning: the mean accuracy was calculated using <5 sample accuracies")
}

```