---
title: "`r gsub('.Rmd', ' ', gsub('_', ' ', knitr::current_input()))`"
author: "`r Sys.getenv('USER')`"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: yes
---

```{r setup, echo=FALSE}

library(tidyverse)
library(dplyr)
library(tidyr)

```

## Summarize results of bulk processing for outlier lead accuracy project

This data comes from the CKCC1 outlier results.

## Load data and create summary tsv (only run once)

```{r, echo=FALSE}

wd <- "/Users/jacquelynroger/Documents/research/treehouse/projects/outlier_lead_accuracy/bulk_processing/"
setwd(wd)

samples <- list.files(path=paste0(wd, "results2/"))
first <- TRUE
for (s in samples) {
  curr_wd <- paste0(wd, "results2/", s, "/")
  setwd(curr_wd)
  leads <- list.files(path=curr_wd) %>%
    lapply(read_tsv) %>%
    bind_rows
  if (first == TRUE) {
    results_all <- leads
    first <- FALSE
  } else {
    results_all <- bind_rows(results_all, leads)
  }
}

names(results_all) <- gsub(" ", "_", names(results_all))

# Add depth data

input_data <- read_tsv("/Users/jacquelynroger/Documents/research/treehouse/projects/outlier_lead_accuracy/bulk_processing/outlier_probability_input_CKCC_2020_06_15.tsv")
depth_data <- unique(input_data %>% select(sample_id, MEND))
depth_data <- rename(depth_data, c("Sample"="sample_id", "MEND_depth"="MEND"))
results_all_with_depth <- merge(results_all, depth_data)

# Add bin info

exp_bins <- c(0, 1, 3, 5, 7, 10, 15)
expression_bins_all <- c("0-1", "1-3", "3-5", "5-7", "7-10", "10-15", "15-20")

results_all_with_depth <- results_all_with_depth %>%
  mutate(MEND_bin = round((MEND_depth/1e6) / 4) * 4,
         MEND_bin = ifelse(MEND_depth>44*1e6, 44, MEND_bin),
         Expression_bin = expression_bins_all[findInterval(Expression, exp_bins)])

# Save data to file to load it in the future

write_tsv(results_all_with_depth, paste0("/Users/jacquelynroger/Documents/research/treehouse/projects/outlier_lead_accuracy/bulk_processing/bulk_results2.tsv"))

```

## Load summary tsv

```{r, echo=FALSE}

bulk_results <- read_tsv("/Users/jacquelynroger/Documents/research/treehouse/projects/outlier_lead_accuracy/bulk_processing/bulk_results2.tsv", col_types=cols())

```

## Number of outlier leads per sample

```{r, echo=FALSE}

# Histogram of number of outlier leads per sample (split by outlier type & fill is depth)

num_leads <- bulk_results %>% group_by(Sample, Type, MEND_bin) %>% tally()

plot1 <- ggplot(num_leads, aes(x=n, fill=as.factor(MEND_bin))) +
  geom_histogram() +
  facet_wrap(~Type) +
  ggtitle("Number of outlier leads per sample")

plot1

```

## Subsample data so all the bins (depth, expression, length) are the same size

```{r, echo=FALSE}

# Look at all the bin sizes

all_bins <- bulk_results %>% tabyl(MEND_bin, Expression_bin)

all_bins

```

## Spectrum of accuracies by depth and expression

```{r, echo=FALSE}

plot2 <- ggplot(bulk_results, aes(x=Mean_Accuracy)) +
  geom_histogram() +
  facet_grid(MEND_bin~Expression_bin) +
  ggtitle("Spectrum of accuracies by depth and expression level")

plot2

plot3 <- ggplot(bulk_results, aes(x=Mean_Accuracy)) +
  geom_histogram() +
  facet_wrap(~MEND_bin) +
  ggtitle("Spectrum of accuracies by depth")

plot3

plot4 <- ggplot(bulk_results, aes(x=Mean_Accuracy)) +
  geom_histogram() +
  facet_wrap(~Expression_bin) +
  ggtitle("Spectrum of accuracies by expression level")

plot4

```