---
title: "`r gsub('.Rmd', ' ', gsub('_', ' ', knitr::current_input()))`"
author: "`r Sys.getenv('USER')`"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: yes
---
  


```{r setup, include = FALSE}

library(tidyverse)
library(janitor)

```

# load
```{r}

samples <- list.files(path = "TH_Eval_014_est10M_UMEND_seqtk_seed_8652", pattern = "summary.tsv", recursive = TRUE)


accuracy_results_raw <- lapply(samples,
                                   function(x) read_tsv(file.path("TH_Eval_014_est10M_UMEND_seqtk_seed_8652", x), col_types = cols(.default = "c")) ) %>% 
                                   # %>% 
                                     #mutate(filename = x)) %>% 
  bind_rows


input_data <- read_tsv("outlier_probability_input_TH_Eval_14_2020_07_13.tsv")
# depth_data <- unique(input_data %>% select(sample_id, MEND))
# depth_data <- rename(depth_data, c("Sample"="sample_id", "MEND_depth" = "MEND"))

confirmed_calls <- input_data %>% 
  filter(sample_id == "TH_Eval_014_est40M_UMEND_seqtk_seed_4956") %>%
  mutate(concordant = TRUE) %>%
  select(Gene, Type, concordant)

accuracy_results <- merge(accuracy_results_raw %>%
                                  filter(Sample != "TH_Eval_014_est40M_UMEND_seqtk_seed_4956"), 
                                input_data %>% select(-sample_id),
                                by=c("Gene", "Type", "Expression", "Threshold")) %>%
  rename_all(~str_replace_all(., ' ', '_')) %>%
  mutate(depth_id = str_replace(Sample, "^.*est([0-9][0-9]*M).*$", "\\1")) %>%
  type_convert %>%
  left_join(confirmed_calls, by=c("Gene", "Type")) %>%
  mutate(concordant = replace_na(concordant, FALSE))
  
table(accuracy_results$concordant, useNA = "always")  


```


```{r}

 ggplot(accuracy_results) + 
  geom_histogram(aes(group=concordant, x=Mean_Accuracy, fill = concordant)) +
  facet_wrap(~Type, ncol = 1) +
  theme_minimal() +
  scale_fill_brewer(palette = "Set1")


 ggplot(accuracy_results) + 
  geom_histogram(aes(group=concordant, x=Expression, fill = concordant)) +
  facet_wrap(concordant~Type, ncol = 1) +
  theme_minimal() +
  scale_fill_brewer(palette = "Set1")

 ggplot(accuracy_results %>% filter(Type == "Up")) + 
  geom_histogram(aes(group=concordant, x=Expression, fill = concordant)) +
  facet_wrap(concordant~Type, ncol = 1) +
  theme_minimal() +
  scale_fill_brewer(palette = "Set1")

 
 ggplot(accuracy_results %>% filter(Type == "Up")) + 
  geom_point(aes(x=Expression, y=Mean_Accuracy, fill = concordant)) +
  facet_wrap(concordant~Type, ncol = 1) +
  theme_minimal() +
  scale_fill_brewer(palette = "Set1")
 
 
 ggplot(accuracy_results %>% filter(Type == "Down")) + 
  geom_point(aes(x=Expression, y=Mean_Accuracy, fill = concordant)) +
  facet_wrap(concordant~Type, ncol = 1) +
  theme_minimal() +
  scale_fill_brewer(palette = "Set1")

 
```



```{r}

 ggplot(accuracy_results) + 
  geom_boxplot(aes(group=concordant, x = concordant, y=Mean_Accuracy, fill = concordant)) +
  facet_wrap(~Type) +
  theme_minimal() +
  scale_fill_brewer(palette = "Set1")


accuracy_results %>%
  tabyl(Type)

```

# Review calls with high accuracy that weren't concordant

```{r}
worst_calcs <- accuracy_results %>% 
  filter(!concordant) %>%
  arrange(desc(Mean_Accuracy)) 
  
worst_calcs[1:10,] %>%
  select(Gene, Type, Expression, Threshold, Sample, Percent_difference, Mean_Accuracy, Minimum_Accuracy, Maximum_Accuracy, effective_length, depth_id, concordant, -Sample)

paste(colnames(worst_calcs[1:10,]), collapse = ", ")

```

# Do any genes shorter than 300 bases have concordant outlier calls?
```{r}
accuracy_results %>%
  filter(effective_length < 300, Type == "Up") %>%
  tabyl(concordant)
  
 accuracy_results %>%
  filter(Type == "Up") %>%
  tabyl(concordant)


  
```


# what are the gene lengths of concordant and non-concordant genes?
```{r}

ggplot(accuracy_results %>% 
         filter(effective_length<10000, Mean_Accuracy>0.9)) +
  geom_boxplot(aes(group=concordant, y=effective_length, fill = concordant)) +
  facet_wrap(~Type) +
  theme_minimal() +
  scale_fill_brewer(palette = "Set1")


ggplot(accuracy_results %>% 
         filter(effective_length<500, Mean_Accuracy>0.9)) +
  geom_histogram(aes(x=effective_length)) +
  facet_grid(concordant~Type) +
  theme_minimal() +
  scale_fill_brewer(palette = "Set1")



ggplot(accuracy_results %>% filter(effective_length<500)) + 
  geom_boxplot(aes(group=concordant, y=Mean_Accuracy, fill = concordant)) +
  facet_wrap(~Type) +
  theme_minimal() +
  scale_fill_brewer(palette = "Set1")


```



```{r}




ggplot(accuracy_results) + 
  geom_boxplot(aes(group=concordant, y=Mean_Accuracy, fill = concordant)) +
  facet_wrap(~Type) +
  theme_minimal() +
  scale_fill_brewer(palette = "Set1")

```

