---
title: "`r gsub('.Rmd', ' ', gsub('_', ' ', knitr::current_input()))`"
author: "`r Sys.getenv('USER')`"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: yes
---
  


```{r setup, include = FALSE}

library(tidyverse)

```

```{r}
old_data_loc <- "/Users/hbeale/Documents/Dropbox/ucsc/projects/gitCode/gene_expression_outlier_accuracy_nov_2020/scratch/TH_Eval_14_2020_07_14/TH_Eval_014_est10M_UMEND_seqtk_seed_8652"


samples <-
  list.files(path = old_data_loc,
             pattern = "summary.tsv",
             recursive = TRUE)

accuracy_results_raw <- lapply(samples,
                               function(x)
                                 read_tsv(
                                   file.path(old_data_loc, x),
                                   col_types = cols(.default = "c")
                                 )) %>% bind_rows
accuracy_results_raw
```

```{r}
new_raw <- read_tsv("/Users/hbeale/Documents/Dropbox/ucsc/projects/gitCode/gene_expression_outlier_accuracy/concordance_analysis/TH_Eval_14_2020_07_14/outlier_probability_output_TH_Eval_14_2020_12_07.tsv.gz") 

new1 <- new_raw %>% filter(Sample == "TH_Eval_014_est10M_UMEND_seqtk_seed_8652") %>%
  rename(Mean_accuracy = `Probability of being an outlier`)

```

```{r}
old1 <- accuracy_results_raw %>%
  rename(Mean_accuracy = `Mean Accuracy`)


combo <- full_join(new1, old1, by=c("Sample", "Gene")) %>%
  type_convert()

ggplot(combo) +
  geom_point(aes(x=Expression.x, y = Expression.y, color = Type.x == Type.y))

ggplot(combo) +
  geom_point(aes(x=Expression.x, y = Expression.y))
             
combo2 <- combo %>%
  mutate(v1_and_v2_accuracies_agree = Mean_accuracy.x == Mean_accuracy.y/100)
table(combo2$v1_and_v2_accuracies_agree)

combo2 %>% filter(v1_and_v2_accuracies_agree)

ggplot(combo) +
  geom_point(aes(x=Mean_accuracy.x, y = Mean_accuracy.y))


```

