---
title: "`r gsub('.Rmd', ' ', gsub('_', ' ', knitr::current_input()))`"
author: "`r Sys.getenv('USER')`"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: yes
---

```{r setup, echo=FALSE}

library(tidyverse)
library(dplyr)
library(tidyr)
library(janitor)

```

# Analyze parent samples to explore gene length binning

```{r, echo=FALSE}

pge <- read_tsv("/Users/jroger/Documents/SPrOut/gene_expression_outlier_accuracy/accuracy_calculation/data/in/per_gene_expression.tsv.gz")

# Histogram of distribution

ggplot(pge, aes(x=effective_gene_length)) +
  geom_histogram() +
  xlim(0, 10000) +
  ggtitle("Distribution of gene lengths")

# Percentiles

quantile(pge$effective_gene_length, probs = seq(0, 1, by= 0.1))

# Accuracies

length_bins <- c(0, 100, 250, 400, 600, 900, 1200, 1500, 2000, 3000, 4000)
length_bins_all <- c("0-100",
                     "100-250",
                     "250-400",
                     "400-600",
                     "600-900",
                     "900-1200",
                     "1200-1500",
                     "1500-2000",
                     "2000-3000",
                     "3000-4000",
                     "4000+")

pgea <- pge %>%
  dplyr::filter(f_expression_at_max_depth_Gt0) %>%
  mutate(within1=(abs(expression-expression_at_max_depth)/expression_at_max_depth)<=0.01,
         within5=(abs(expression-expression_at_max_depth)/expression_at_max_depth)<=0.05,
         within10=(abs(expression-expression_at_max_depth)/expression_at_max_depth)<=0.10,
         within25=(abs(expression-expression_at_max_depth)/expression_at_max_depth)<=0.25,
         within50=(abs(expression-expression_at_max_depth)/expression_at_max_depth)<=0.50,
         length_bin = length_bins_all[findInterval(effective_gene_length, length_bins)],
         lb = length_bins[findInterval(effective_gene_length, length_bins)])

# Plot accuracies

pgea_fractions <- pgea %>%
  group_by(length_bin, lb) %>%
  summarize(n=n(),
            frac1=sum(within1)/n(),
            frac5=sum(within5)/n(),
            frac10=sum(within10)/n(),
            frac25=sum(within25)/n(),
            frac50=sum(within50)/n())

ggplot(pgea_fractions, aes(x=lb)) +
  geom_line(aes(y=frac1)) +
  geom_line(aes(y=frac5)) +
  geom_line(aes(y=frac10)) +
  geom_line(aes(y=frac25)) +
  geom_line(aes(y=frac50)) +
  ggtitle("Accuracies by gene bin")
  

```

### Nov 23: reevaluate length bins

```{r}

# Compute vertical distance between accuracy fraction of first and last bin
# Do this for the within10 since that's a good middle ground

vdist10 <- pgea_fractions$frac10[9] - pgea_fractions$frac10[1]

# Divide by 4 and find corresponding length bin for each boundary

lbs10 <- seq(pgea_fractions$frac10[1],pgea_fractions$frac10[9], vdist10/4)

# Plot lines from within 10 (middle ground) to see where length bin boundaries should be
ggplot(pgea_fractions, aes(x=lb)) +
  geom_line(aes(y=frac10)) +
  ggtitle("Accuracies by gene bin") +
  geom_hline(yintercept=lbs10, color = "red")

```